services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - local/development.env
    environment:
      - DJANGO_SETTINGS_MODULE=app_core.settings.development
