services:
  db:
    container_name: db-dev
    build:
      context: ./config/postgres
    env_file:
      - local/development.env
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  django:
    container_name: django-dev
    build:
      context: .
      args:
        REQUIREMENTS_FILE: requirements-dev.txt
    volumes:
      - .:/usr/src/app

    ports:
      - "8000:8000"
    env_file:
      - local/development.env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.development
    depends_on:
      - db


volumes:
  pgdata_dev:
    name: pgdata_dev_volume