[tool.black]
line-length = 119
target-version = ['py39']

[tool.ruff]
line-length = 119
select = ["E", "F", "W", "C90"]
ignore = ["E501", "F403"]

[tool.isort]
profile = "black"

[tool.mypy]
strict = true
python_version = "3.9"

[tool.pylint.MASTER]
ignore = ["E501", "C0114"]

authors = ["manulabricole <emmanuel.barriol@gmail.com>"]